version: '3.8'

services:
  db:
    image: postgres:15
    container_name: novaparcel-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: novaparcel
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: novaparcel-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@novaparcel.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./servers.json:/pgadmin4/servers.json
